language: go
go:
    - 1.2
    - 1.3
    - tip
install:
    - go get github.com/bcbroussard/k8s-ldap/asn1-ber
    - go get github.com/bcbroussard/k8s-ldap/ldap
    - go get code.google.com/p/go.tools/cmd/cover || go get golang.org/x/tools/cmd/cover
    - go build -v ./...
script:
    - go test -v -cover ./...
